name: hourly-london-weather-nft-update-v2
execution: sequential
trigger:
  type: time-based
  repeatEvery: "*/5 * * * *" 

actions:
  - name: GetLondonWeather
    type: api
    apiEndpoint: "https://api.open-meteo.com/v1/forecast?latitude=51.5072&longitude=-0.1276&current=weather_code&timezone=Europe/London"

  - name: UpdateNFTOnChain
    type: call
    chainID: 80002 
    targetContract: "0x4eb0297409edfab76d08db836f5ca49088d7c4ad" 
    targetFunction: "updateTokenURI"
    targetParams:
      - "https://weather-morph.vercel.app/api?weather={{actions.GetLondonWeather.response.current.weather_code}}"
